// Tactiques Recta — protocole de décision du C.G.U., directives brèves
// et cryptiques (façon Stratégies Obliques, durcies pour la Rectitude).
// 2 protocoles : opératoire (froid) + paranoia (surveillance).
// Fournies par Olivier ; sélection déterministe par seed.

import { rngFor } from "./rng";

export interface Tactique { n: number; code: string; protocole: string; seg: string; segLabel: string; text: string; }

export const TACTIQUES: Tactique[] = [
  { n: 1, code: "RT-001", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Isole l'élément le plus bruyant et coupe son alimentation." },
  { n: 2, code: "RT-002", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Si la solution demande du courage, elle est mal calculée. Cherche la solution froide." },
  { n: 3, code: "RT-003", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Considère la résistance non pas comme une opposition, mais comme une friction mécanique prévisible." },
  { n: 4, code: "RT-004", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Quel protocole appliques-tu par simple habitude ? Abroge-le immédiatement." },
  { n: 5, code: "RT-005", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Réduis le dilemme à une simple soustraction : qu'est-ce qui doit disparaître pour que l'ordre revienne ?" },
  { n: 6, code: "RT-006", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "La pitié est un reflux biologique. Attends dix secondes qu'il passe, puis agis." },
  { n: 7, code: "RT-007", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Ne cherche pas à convaincre. Modifie les paramètres pour qu'il n'y ait plus d'alternative." },
  { n: 8, code: "RT-008", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Si le plan échoue, c'est un échec systémique. Où se situe le défaut d'alignement ?" },
  { n: 9, code: "RT-009", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Traite le chaos ambiant comme une suite de chiffres non triés. Filtre et classe." },
  { n: 10, code: "RT-010", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "La parole consomme de l'oxygène et du temps. Remplace la prochaine déclaration par une directive binaire." },
  { n: 11, code: "RT-011", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Quelle faille s'ouvre si tu retires le facteur \"confiance\" de ton dispositif ? Remplis-la de surveillance." },
  { n: 12, code: "RT-012", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Ne répare pas une structure déviante. Accélère sa chute pour rebâtir sur une base plane." },
  { n: 13, code: "RT-013", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "L'attachement à un outil obsolète est une faute de gestion. Remplace-le, peu importe son histoire." },
  { n: 14, code: "RT-014", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Qu'est-ce qui t'empêche de dormir ? C'est la variable à éliminer en priorité." },
  { n: 15, code: "RT-015", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "N'attends pas le signal parfait. Le bruit de fond contient déjà la tendance." },
  { n: 16, code: "RT-016", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Agis comme si chaque intermédiaire était un vecteur potentiel de corruption. Raccourcis la chaîne." },
  { n: 17, code: "RT-017", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "La colère est un pic d'énergie inutile. Convertis-la instantanément en précision chirurgicale." },
  { n: 18, code: "RT-018", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Si le calcul est exact, le résultat est inévitable. Ne regarde pas l'impact, regarde le graphique." },
  { n: 19, code: "RT-019", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "L'anomalie n'est pas un mystère, c'est une donnée mal indexée. Trouve sa case." },
  { n: 20, code: "RT-020", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Ignore les intentions déclarées. Seul le déplacement des masses de données fait foi." },
  { n: 21, code: "RT-021", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Rends les critères de succès si stricts que seule la Rectitude peut les franchir." },
  { n: 22, code: "RT-022", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Divise l'objectif par dix. Répète l'opération dix fois plus vite." },
  { n: 23, code: "RT-023", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "La souffrance périphérique n'apparaît pas dans le bilan comptable de l'entité. Ignore-la." },
  { n: 24, code: "RT-024", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Quel est le coût exact de ton hésitation à la minute ? Fais le calcul et décide." },
  { n: 25, code: "RT-025", protocole: "operatoire", seg: "ALPHA", segLabel: "L'Érosion des Variables", text: "Ne cherche pas le consensus, cherche la structure qui rend la dissidence impossible." },
  { n: 26, code: "RT-026", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Reste immobile jusqu'à ce que l'agitation de l'adversaire révèle sa ligne de moindre résistance." },
  { n: 27, code: "RT-027", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Le mouvement permanent simule l'efficacité. Arrête-toi et recalibre." },
  { n: 28, code: "RT-028", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Si la situation exige une exception, c'est que la règle a été mal conçue. Corrige la règle." },
  { n: 29, code: "RT-029", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "La tradition est un algorithme mort. Efface le cache." },
  { n: 30, code: "RT-030", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Que ferais-tu si tu savais que personne ne viendra valider ton action ? Fais-le maintenant." },
  { n: 31, code: "RT-031", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Ne confonds pas la complexité du sous-marin avec le désordre de la surface. Garde la façade minimaliste." },
  { n: 32, code: "RT-032", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Le doute est une fuite de pression. Colmate-la en revenant aux faits bruts." },
  { n: 33, code: "RT-033", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Un échec n'est qu'une seconde chance de bien faire, à condition d'avoir purgé la cause de la faute." },
  { n: 34, code: "RT-034", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Considère chaque individu de l'équation comme un simple commutateur : ouvert ou fermé." },
  { n: 35, code: "RT-035", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "La transparence totale est une erreur tactique. Reste opaque, sois prévisible uniquement dans l'efficacité." },
  { n: 36, code: "RT-036", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Si tu ressens de la fierté, ton action est polluée. Le succès brillant est aussi insupportable que l'échec." },
  { n: 37, code: "RT-037", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Élimine l'adjectif. Ne garde que le verbe et le complément dans tes transmissions." },
  { n: 38, code: "RT-038", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "La flexibilité est le début de la dérive. Sois rigide comme le cadre." },
  { n: 39, code: "RT-039", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Pense à la structure d'un cristal : froide, parfaite, immuable. Deviens ce cristal." },
  { n: 40, code: "RT-040", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Le compromis est une équation mal résolue où les deux parties perdent. Refuse-le." },
  { n: 41, code: "RT-041", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Ne cherche pas à être compris, cherche à être exécuté." },
  { n: 42, code: "RT-042", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "L'urgence est un piège de l'esprit. Prends le temps d'appliquer la procédure la plus lente mais la plus sûre." },
  { n: 43, code: "RT-043", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Que dicte le bon sens ? Fais exactement l'inverse si la logique pure le démontre." },
  { n: 44, code: "RT-044", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "L'erreur n'est pas fatale, mais persister dans la subjectivité est un crime contre la Rectitude." },
  { n: 45, code: "RT-045", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Ne tolère aucun angle mort dans ton périmètre, même s'il faut raser ce qui s'y trouve." },
  { n: 46, code: "RT-046", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Si la vérité est inconfortable, c'est ton confort qui doit être réformé, pas la vérité." },
  { n: 47, code: "RT-047", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "L'unanimité est suspecte. Cherche le dissident silencieux et étudie sa logique." },
  { n: 48, code: "RT-048", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Ne laisse aucune trace de ton intention avant l'impact final." },
  { n: 49, code: "RT-049", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "La Rectitude ne négocie pas avec le désordre. Elle le subsume ou l'efface." },
  { n: 50, code: "RT-050", protocole: "operatoire", seg: "BETA", segLabel: "L'Immobilisme Rectiligne", text: "Pense en termes de cycles de maintenance. Qu'est-ce qui a besoin d'être nettoyé aujourd'hui ?" },
  { n: 51, code: "RT-051", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Remplace l'intuition par une série de trois tests empiriques." },
  { n: 52, code: "RT-052", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Si le plan dépend d'une seule personne, change le plan immédiatement." },
  { n: 53, code: "RT-053", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "La peur de l'échec est le premier indice de la défaillance. Remplace l'agent ou la méthode." },
  { n: 54, code: "RT-054", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Utilise la force de l'adversaire pour sceller sa propre trajectoire." },
  { n: 55, code: "RT-055", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Ne crée pas de nouvelles règles. Applique les anciennes avec une sévérité accrue." },
  { n: 56, code: "RT-056", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Le secret le mieux gardé est celui dont la clé n'a aucune valeur émotionnelle." },
  { n: 57, code: "RT-057", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Réduis tes besoins au strict minimum. Moins tu dépenses, moins tu dépends." },
  { n: 58, code: "RT-058", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Considère la crise comme une simple accélération du calendrier. Reste à l'heure." },
  { n: 59, code: "RT-059", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "L'empathie envers la cible ralentit la cinétique du projectile. Coupe le flux visuel." },
  { n: 60, code: "RT-060", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Quelle est la décision la plus impopulaire ? C'est souvent celle qui préserve l'essentiel." },
  { n: 61, code: "RT-061", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Ne cherche pas l'origine du problème, bloque ses conséquences immédiates." },
  { n: 62, code: "RT-062", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "La perfection esthétique de la Rectitude réside dans l'absence totale de débris. Ramasse tout." },
  { n: 63, code: "RT-063", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Si deux rapports se contredisent, élimine les deux et collecte toi-même les données brutes." },
  { n: 64, code: "RT-064", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "L'excès de zèle est une déviance. Fais exactement ce qui est demandé, rien de plus, rien de moins." },
  { n: 65, code: "RT-065", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Considère ton corps comme une unité de confinement. Ne laisse aucune tension altérer ton jugement." },
  { n: 66, code: "RT-066", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "La Rectitude n'a pas besoin de justification. Son existence est sa propre preuve." },
  { n: 67, code: "RT-067", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Quel est le maillon le plus faible de ton équipe ? Donne-lui la tâche la plus simple ou isole-le." },
  { n: 68, code: "RT-068", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "N'essaie pas de combler le vide. Le vide est une zone de contrôle parfaite." },
  { n: 69, code: "RT-069", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Le passé n'est qu'une suite d'instructions validées ou invalidées. Ne le regrette pas." },
  { n: 70, code: "RT-070", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Si la cible change de stratégie, reste sur ta ligne. La constance brise l'opportunisme." },
  { n: 71, code: "RT-071", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "La colère de l'ennemi est une faille dans sa logique. Exploite-la sans tarder." },
  { n: 72, code: "RT-072", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Ne confonds pas la vitesse et la précipitation. La Rectitude est une force constante, pas une explosion." },
  { n: 73, code: "RT-073", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Quelle variable as-tu introduite par pure vanité ? Retire-la." },
  { n: 74, code: "RT-074", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Le silence de l'adversaire est une collecte de données. Interromps son flux." },
  { n: 75, code: "RT-075", protocole: "operatoire", seg: "GAMMA", segLabel: "L'Anatomie du Vecteur", text: "Ne regarde pas la montagne, regarde le point d'ancrage de ton prochain pas." },
  { n: 76, code: "RT-076", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Si la solution est belle, méfie-toi. La Rectitude est souvent brute et sans fioritures." },
  { n: 77, code: "RT-077", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "L'obéissance passive est une forme de paresse. La Rectitude exige une adhésion active de la logique." },
  { n: 78, code: "RT-078", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Élimine le besoin de récompense. Le fonctionnement correct du système est ton seul salaire." },
  { n: 79, code: "RT-079", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Si le doute persiste, choisis l'option qui demande le moins d'interactions humaines." },
  { n: 80, code: "RT-080", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "La rumeur est une infection. Traite-la par la mise en quarantaine des sources." },
  { n: 81, code: "RT-081", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Ne cherche pas à laisser une marque dans l'histoire, cherche à stabiliser le présent." },
  { n: 82, code: "RT-082", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Considère la fatigue comme une simple baisse de tension. Augmente le courant ou repose l'unité." },
  { n: 83, code: "RT-083", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "L'ordre n'est pas un état naturel, c'est une conquête permanente contre l'entropie." },
  { n: 84, code: "RT-084", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Si la cible demande grâce, elle utilise un code obsolète. N'y réponds pas." },
  { n: 85, code: "RT-085", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "La Rectitude ne tolère pas le \"presque\". 99% d'efficacité est une défaillance système." },
  { n: 86, code: "RT-086", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Quel est l'impact de ton action sur les infrastructures de base ? Protège la structure d'abord." },
  { n: 87, code: "RT-087", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Ne te laisse pas séduire par l'originalité d'une solution. La monotonie du succès est préférable." },
  { n: 88, code: "RT-088", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Si le protocole est lourd, simplifie-le par l'automatisation. Moins d'humains, moins de fautes." },
  { n: 89, code: "RT-089", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "La nostalgie est un bug de mémoire. Formate le secteur concerné." },
  { n: 90, code: "RT-090", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Ne prends pas de risques calculés si une option sans risque, bien que plus lente, existe." },
  { n: 91, code: "RT-091", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Considère chaque conflit comme un simple problème d'allocation de ressources. Rééquilibre la balance." },
  { n: 92, code: "RT-092", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "L'autorité ne se négocie pas, elle s'exerce par la constance du vecteur." },
  { n: 93, code: "RT-093", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Si la logique te mène à une conclusion absurde, vérifie tes postulats. La Rectitude ne produit pas d'absurdité." },
  { n: 94, code: "RT-094", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "La pitié pour le saboteur est un sabotage de la sécurité collective. Applique la peine maximale." },
  { n: 95, code: "RT-095", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Ne cherche pas à être indispensable. Une structure parfaite fonctionne même si tu disparais." },
  { n: 96, code: "RT-096", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Quel est le facteur limitant de ton attention en ce moment ? Isole-toi de ce stimulus." },
  { n: 97, code: "RT-097", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "La Rectitude est une ligne droite dans un univers courbe. Ne plie pas." },
  { n: 98, code: "RT-098", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Si l'action génère du regret, c'est que la décision a été prise avec le cœur, pas avec la grille de calcul." },
  { n: 99, code: "RT-099", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "L'ordre est le silence du chaos. Fais taire les dissonances." },
  { n: 100, code: "RT-100", protocole: "operatoire", seg: "DELTA", segLabel: "La Synthèse Absolue", text: "Rappelle-toi que le C.G.U. ne demande pas ton avis, il demande ta conformité. Le calcul est clos." },
  { n: 101, code: "RT-101", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "S'ils sourient, c'est qu'ils ont trouvé une faille dans ton protocole. Cherche-la." },
  { n: 102, code: "RT-102", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Ne dis rien. Laisse leur propre silence les forcer à se trahir." },
  { n: 103, code: "RT-103", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Accepte leur aide, puis cherche immédiatement comment ils comptent l'utiliser contre toi." },
  { n: 104, code: "RT-104", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Consigne leur retard de deux minutes. Ce n'est pas un accident, c'est un test de ton autorité." },
  { n: 105, code: "RT-105", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Note précisément qui approuve tes décisions trop vite. Ce sont tes premiers opposants." },
  { n: 106, code: "RT-106", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Si la solution est simple, c'est qu'on t'a caché la moitié des données pour te faire échouer." },
  { n: 107, code: "RT-107", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Laisse-les commettre leur erreur. Intervenir trop tôt les empêcherait d'être punis." },
  { n: 108, code: "RT-108", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Ne refuse pas leur demande. Rends le formulaire d'approbation si complexe qu'ils abandonneront d'eux-mêmes." },
  { n: 109, code: "RT-109", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Isole l'élément qui veut toujours \"bien faire\". C'est le plus imprévisible du réseau." },
  { n: 110, code: "RT-110", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Rappelle-leur le règlement au moment exact où ils pensaient avoir réussi." },
  { n: 111, code: "RT-111", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Leur dévouement est suspect. Personne ne sert l'entité sans un agenda caché. Trouve le leur." },
  { n: 112, code: "RT-112", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "S'ils demandent des éclaircissements, c'est pour pouvoir rejeter la faute sur tes ordres en cas d'échec." },
  { n: 113, code: "RT-113", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Réponds à leurs questions complexes par un simple : \"Le protocole est pourtant clair.\"" },
  { n: 114, code: "RT-114", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Ne coupe pas la parole. Laisse-les s'enfoncer dans leur propre rhétorique." },
  { n: 115, code: "RT-115", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Considère chaque compliment d'un subordonné comme une tentative d'altérer ton objectivité." },
  { n: 116, code: "RT-116", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Fais planer le doute sur la prochaine inspection. L'incertitude maintient l'alignement." },
  { n: 117, code: "RT-117", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "S'ils s'unissent pour un projet, c'est le début d'une cellule dissidente. Divise les tâches." },
  { n: 118, code: "RT-118", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Ne les accuse pas directement. Pose des questions rhétoriques dont la réponse valide leur incompétence." },
  { n: 119, code: "RT-119", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Observe qui regarde la porte pendant les réunions d'alignement. C'est là que se trouve leur esprit." },
  { n: 120, code: "RT-120", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "L'erreur qu'ils ont commise aujourd'hui était déjà en germe dans leur regard hier." },
  { n: 121, code: "RT-121", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Reste en retrait. Laisse un autre prendre l'initiative pour qu'il prenne aussi la responsabilité de l'impact." },
  { n: 122, code: "RT-122", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "S'ils prétendent avoir compris, exige une démonstration écrite en trois exemplaires." },
  { n: 123, code: "RT-123", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "La politesse excessive est la façade de la trahison. Durcis le ton." },
  { n: 124, code: "RT-124", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Ne corrige pas leur rapport. Renvoie-le simplement avec la mention : \"À retravailler.\"" },
  { n: 125, code: "RT-125", protocole: "paranoia", seg: "ALPHA", segLabel: "La Traque des Intentions Cachées", text: "Ils parlent de toi quand tu quittes la pièce. Fais en sorte qu'ils aient une bonne raison de le faire." },
  { n: 126, code: "RT-126", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Ne partage jamais la phase finale du plan. Ils n'ont besoin de connaître que leur maillon." },
  { n: 127, code: "RT-127", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Si un agent devient indispensable, c'est qu'il a saboté la redondance du système pour se protéger. Rends-le obsolète." },
  { n: 128, code: "RT-128", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Sois parfaitement prévisible dans ta froideur. C'est le seul moyen de détecter leurs variations." },
  { n: 129, code: "RT-129", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Leur enthousiasme est une insulte à la rigueur du calcul. Refroidis l'ambiance." },
  { n: 130, code: "RT-130", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Ne dis pas non, dis : \"C'est noté, nous verrons si les ressources le permettent.\" (Elles ne le permettront pas)." },
  { n: 131, code: "RT-131", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Garde une preuve de chaque petite défaillance. Elles serviront à construire le dossier le moment venu." },
  { n: 132, code: "RT-132", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "S'ils essaient de deviner tes intentions, change de vecteur sans les prévenir pour tester leur réactivité." },
  { n: 133, code: "RT-133", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "La transparence n'est qu'un mot qu'ils utilisent pour fouiller dans tes fichiers. Verrouille les accès." },
  { n: 134, code: "RT-134", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Laisse-les croire qu'ils ont eu une bonne idée, puis applique le protocole standard en leur attribuant le mérite de la monotonie." },
  { n: 135, code: "RT-135", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Si un rapport est trop parfait, c'est qu'il a été rédigé pour masquer une anomalie systémique." },
  { n: 136, code: "RT-136", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Ne réponds pas immédiatement à leurs transmissions. Laisse l'anxiété faire le travail de recadrage." },
  { n: 137, code: "RT-137", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Ils te croient paranoïaque parce que leur propre duplicité n'a pas encore été indexée." },
  { n: 138, code: "RT-138", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Rappelle-leur gentiment leur échec de l'année dernière au moment où ils demandent une promotion." },
  { n: 139, code: "RT-139", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "La confiance est une vulnérabilité logicielle. N'installe pas ce patch." },
  { n: 140, code: "RT-140", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "S'ils demandent de l'autonomie, c'est qu'ils ne supportent plus la Rectitude. Augmente la surveillance." },
  { n: 141, code: "RT-141", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Ne critique pas leur travail en public. Contente-toi d'un soupir audible pendant leur présentation." },
  { n: 142, code: "RT-142", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Chaque document partagé doit contenir un marqueur unique pour identifier la source en cas de fuite." },
  { n: 143, code: "RT-143", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "S'ils te demandent comment tu vas, cherche ce qu'ils ont à se faire pardonner." },
  { n: 144, code: "RT-144", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Le cadre est ton seul rempart contre leur paresse naturelle. Ne lâche pas un millimètre." },
  { n: 145, code: "RT-145", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Ne prends jamais position le premier. Attends de voir qui s'expose pour ajuster ton tir." },
  { n: 146, code: "RT-146", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Leur vie privée est le laboratoire où ils cultivent leur déviance. Surveille les connexions." },
  { n: 147, code: "RT-147", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "S'ils se plaignent du manque de moyens, rappelle-leur que l'efficacité ne dépend pas du confort." },
  { n: 148, code: "RT-148", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Un échec de leur part est une confirmation de ton diagnostic initial. Tu le savais." },
  { n: 149, code: "RT-149", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "N'explique pas pourquoi tu refuses. L'explication est une faiblesse qui ouvre la porte à la négociation." },
  { n: 150, code: "RT-150", protocole: "paranoia", seg: "BETA", segLabel: "Le Cloisonnement des Risques", text: "Sois le miroir de leur propre méfiance, mais avec trois niveaux de cryptage supplémentaires." },
  { n: 151, code: "RT-151", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Si la cible change de comportement, c'est qu'elle a détecté ton observation. Feins le désintérêt." },
  { n: 152, code: "RT-152", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Donne-leur exactement ce qu'ils ont demandé, surtout si tu sais que cela va saturer leur service." },
  { n: 153, code: "RT-153", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Leur créativité est une tentative désespérée de masquer leur incapacité à suivre une procédure simple." },
  { n: 154, code: "RT-154", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Ne hausse jamais le ton. La Rectitude s'exprime dans le murmure d'un verdict inéluctable." },
  { n: 155, code: "RT-155", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "S'ils te demandent un conseil, renvoie-les à la ligne 42 du manuel général." },
  { n: 156, code: "RT-156", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Garde tes yeux fixés sur leurs mains, jamais sur leur visage. Le visage ment, les doigts trahissent la tension." },
  { n: 157, code: "RT-157", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Ne sabote pas leur projet. Laisse simplement les validations administratives prendre le temps nécessaire." },
  { n: 158, code: "RT-158", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Leur besoin de reconnaissance est une faille psychologique. Exploite-la en la leur refusant." },
  { n: 159, code: "RT-159", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "S'ils s'excusent, c'est qu'ils calculent déjà le coût de leur prochaine faute." },
  { n: 160, code: "RT-160", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Ne montre aucune impatience. L'usure du temps est ton alliée la plus fidèle contre leur résistance." },
  { n: 161, code: "RT-161", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Ils pensent que tu oublies. La Rectitude n'efface jamais l'historique." },
  { n: 162, code: "RT-162", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Réduis les réunions au strict minimum factuel : \"Données. Résultats. Écarts. Fin de transmission.\"" },
  { n: 163, code: "RT-163", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "S'ils essaient d'entrer dans ton espace personnel, c'est pour évaluer tes défenses. Reste derrière le comptoir." },
  { n: 164, code: "RT-164", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Chaque feedback doit commencer par : \"Bien que les attentes fussent minimales, vous avez réussi à...\"" },
  { n: 165, code: "RT-165", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "La compassion est le piège qu'ils te tendent pour que tu partages la responsabilité de leur chute." },
  { n: 166, code: "RT-166", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Ne valide pas leur succès. Rappelle-leur simplement que c'est ce pour quoi ils ont été configurés." },
  { n: 167, code: "RT-167", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "S'ils changent de ton, c'est qu'ils ont trouvé un nouvel allié dans la hiérarchie. Identifie-le." },
  { n: 168, code: "RT-168", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Rends tes directives si vagues qu'ils devront prendre des risques pour les exécuter, puis punis l'excès de zèle." },
  { n: 169, code: "RT-169", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Leur solidarité s'arrête là où commence le rapport de fin d'année. Utilise ce levier." },
  { n: 170, code: "RT-170", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Ne refuse pas la discussion. Planifie-la à une heure où ils seront trop fatigués pour argumenter." },
  { n: 171, code: "RT-171", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "S'ils t'évitent dans les couloirs, c'est que le sabotage est déjà en cours. Active les contre-mesures." },
  { n: 172, code: "RT-172", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Leur liberté de pensée s'arrête là où commence l'intégrité du C.G.U. Autant dire nulle part." },
  { n: 173, code: "RT-173", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Ne leur donne pas d'ordres directs. Dis plutôt : \"Il serait regrettable que cette tâche ne soit pas priorisée.\"" },
  { n: 174, code: "RT-174", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "Chaque sourire de ta part doit être perçu comme une menace de mise à pied." },
  { n: 175, code: "RT-175", protocole: "paranoia", seg: "GAMMA", segLabel: "La Cinétique Passive", text: "L'ordre est parfait quand plus personne n'ose poser de questions de peur de révéler son ignorance." },
  { n: 176, code: "RT-176", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils prétendent travailler en équipe, cherche qui fait le travail et qui prend le crédit." },
  { n: 177, code: "RT-177", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Ne les laisse pas fixer les délais. Donne-leur la moitié du temps estimé pour tester leur gestion du stress." },
  { n: 178, code: "RT-178", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "La Rectitude ne tolère aucun secret de leur part, mais exige une opacité totale de la tienne." },
  { n: 179, code: "RT-179", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils te demandent une faveur, enregistre la demande comme une preuve de leur incapacité à suivre le protocole." },
  { n: 180, code: "RT-180", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Leur bonheur est une anomalie statistique dans une zone industrielle. Corrige le signal." },
  { n: 181, code: "RT-181", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Ne dis pas que c'est faux. Dis : \"C'est une perspective intéressante pour quelqu'un de votre rang.\"" },
  { n: 182, code: "RT-182", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils essaient de te rassurer, c'est que la situation est déjà hors de contrôle. Prends les commandes." },
  { n: 183, code: "RT-183", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "La paranoïa n'est qu'une lucidité supérieure face à un environnement peuplé d'humains défaillants." },
  { n: 184, code: "RT-184", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Ne leur montre jamais tes notes. Laisse-les deviner ce qui est écrit à leur sujet." },
  { n: 185, code: "RT-185", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils s'excusent pour leur incompétence, accepte l'excuse et intègre-la officiellement à leur dossier." },
  { n: 186, code: "RT-186", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "L'harmonie apparente de leur service cache une complicité dans la déviance. Casse le groupe." },
  { n: 187, code: "RT-187", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Ne leur donne pas le droit à l'erreur, mais donne-leur toute la latitude pour la commettre." },
  { n: 188, code: "RT-188", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils demandent pourquoi, réponds : \"Parce que le calcul l'exige.\" La discussion est close." },
  { n: 189, code: "RT-189", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Leur loyauté s'achète avec des ressources que l'entité ne peut gaspiller. Préfère la peur, elle est gratuite." },
  { n: 190, code: "RT-190", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Ne sois pas agressif, sois simplement d'une froideur si tranchante qu'ils s'autocensureront." },
  { n: 191, code: "RT-191", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils te regardent dans les yeux, c'est un défi. S'ils baissent les yeux, c'est un aveu. Traite les deux de la même manière." },
  { n: 192, code: "RT-192", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Chaque initiative non planifiée est un clou de plus dans le cercueil de leur carrière au C.G.U." },
  { n: 193, code: "RT-193", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Ne cherche pas à savoir s'ils t'aiment. Assure-toi qu'ils craignent la ligne rouge de ton graphique." },
  { n: 194, code: "RT-194", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils t'offrent un café, demande-toi ce qu'ils essaient de te faire avaler au sens propre comme au figuré." },
  { n: 195, code: "RT-195", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Leur existence même est une variable instable. Rends-la aussi rigide que possible." },
  { n: 196, code: "RT-196", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Ne leur dis pas qu'ils ont échoué. Laisse le système envoyer la notification automatique." },
  { n: 197, code: "RT-197", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils essaient de simplifier la procédure, c'est pour pouvoir tricher sans laisser de traces." },
  { n: 198, code: "RT-198", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "La Rectitude n'est pas une question de justice, c'est une question de contrôle. Et le contrôle commence par la méfiance." },
  { n: 199, code: "RT-199", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "S'ils pensent que tu as terminé, c'est là que tu tires la carte suivante." },
  { n: 200, code: "RT-200", protocole: "paranoia", seg: "DELTA", segLabel: "Le Verrouillage du Cadre", text: "Rappelle-toi : \"C'est un échec\" est la phrase qui les attend au moindre faux pas. Sois celui qui la prononce." },
];

/** Une tactique déterministe par seed (pour l'affiche + la légende). */
export function tactiqueFor(seed: string): Tactique {
  const rng = rngFor(seed, "tactique");
  return TACTIQUES[(rng() * TACTIQUES.length) | 0];
}
